title: Elijah spec-docs
logo: /assets/img/letter-e_9074084.png
description: Something almost official
google_analytics:
github_username: tripleo1

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

theme: minima

show_downloads: true
#remote_theme: "mmistakes/minimal-mistakes@4.26.2"
remote_theme: "jsanz/gh-pages-minima-starter"

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

search: true
rss: rss


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
